### ISSUE TITLE
support dumping tapes without tape markers

### ISSUE THREAD

**Issue by ams** [Chaosnet/chaosnet-tools#18]
Would be nice if RTAPE could dump tapes without tape markers.

AFAIK, they are not needed if you are dumping over Chaosnet (.tap might be a different story).

**Comment by bictorv** [comment]
Please elaborate - I don't understand the issue(s)?

**Comment by eswenson1** [comment]
Yeah. Me too. What value would removing the tape marks have? Seems better that it write tape marks, making the resulting “file” readable with tape tools that expect marks.

**Comment by eswenson1** [comment]
If you’re using emacs to extract files from dumps, sure. But who would be silly enough to do that? :-) Wouldn’t it be better to simply write a real tape file extract too for those tapes?

**Comment by bictorv** [comment]
There are tools for extracting LMFL tapes already: you sent me one, and Lars did too (in an email conversation from February this year).

**Comment by ams** [comment]
There are sadly multiple formats of LMFL -- and sometimes I have tapes without markers. :-). And the ones that I sent don't do the work I need them to (modification of LMFL headers .. and other nonsense)

@larsbrinkhoff What did you send?

**Comment by eswenson1** [comment]
I’d like a copy of said tool. The one I have doesn’t work on many LMFL tapes I’ve tried.

**Comment by bictorv** [comment]
Look in larsbrinkhoff pdp10-its-disassembler, some branch.

**Comment by ams** [comment]
It is on the lars/lmfl-dump branch -- and this is very much incomplete.

**Comment by larsbrinkhoff** [comment]
I'm not sure what "tape markers" means here.  Usually a "tape mark" is a distinct pattern on the tape which separates records/blocks into "files".  Two marks in a row is the logical end of tape.

But I suppose you mean the SIMH tape format fields which frame records in a tape image file; they also describe some other metadata like errors.  I suppose it's not overly cumbersome to support various types of tape image formats, one which could be this "marker-less" type.  *On the other hand*, it's quite trivial to "unblock" (as it's sometimes called) a tape (physical or image) to a linear file.

**Comment by larsbrinkhoff** [comment]
Yes, my LMFL extraction tool is very crude.  Possibly only good enough to list some ToTS tapes.  (There are more than just PDP-10 tapes there, you know.)

**Comment by bictorv** [comment]
> On the other hand, it's quite trivial to "unblock" (as it's sometimes called) a tape (physical or image) to a linear file.

Probably around 10 lines of code in a suitable high-level language?
