### ISSUE TITLE
Trying to start rtape on macos gives error

### ISSUE THREAD

**Issue by eswenson1** [Chaosnet/chaosnet-tools#3]
Trying to start rtape on macOS, I get this error:

```
➜  tapes ../rtape -v
Peer : Unknown operation: 0
```

Is this supposed to work on macOS?

Compiling it under macOS gives these warnings:

```
➜  chaosnet-tools git:(lars/rtape) make
cc -Wall -W -g   -c -o gw.o gw.c
cc -Wall -W -g   -c -o chaos.o chaos.c
cc  -o gw gw.o chaos.o
cc -Wall -W -g   -c -o rtape.o rtape.c
rtape.c:750:5: warning: 'daemon' is deprecated: first deprecated in macOS 10.5 - Use posix_spawn APIs instead. [-Wdeprecated-declarations]
    daemon(1, 1);
    ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdlib.h:299:6: note: 'daemon' has been explicitly marked deprecated here
int      daemon(int, int) __DARWIN_1050(daemon) __OSX_AVAILABLE_BUT_DEPRECATED_MSG(__MAC_10_0, __MAC_10_5, __IPHONE_2_0, __IPHONE_2_0, "Use posix_spawn APIs instead.") __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
         ^
1 warning generated.
cc -Wall -W -g   -c -o tape-image.o tape-image.c
cc  -o rtape rtape.o chaos.o tape-image.o
```

**Comment by larsbrinkhoff** [comment]
> Is this supposed to work on macOS?

I don't have any mac myself, so I can't test it.  But I'm not against someone else supplying changes to make it work.

**Comment by eswenson1** [comment]
Ok, I’ll try debugging but I’m wondering if the combination of lars/rtape branch of this repo and the cleaning-windows branch of the chaosnet-bridge repo is known to work? I wasn’t able to get this to work on Ubuntu 22.04 either. See other issue.

**Comment by larsbrinkhoff** [comment]
As far as I know, no combination is known to work fully.  I will test @bictorv's fixes on the cleaning-windows branch.

**Comment by bictorv** [comment]
The rtape from "a couple of days ago" in combination with the cleaning-windows cbridge (which doesn't contain rtape) works many times, but sometimes gives errors. But not the error Eric shows above.

Where is rtape now? Is it here in chaosnet-tools, or in the cbridge branch?

**Comment by larsbrinkhoff** [comment]
rtape is herein chaosnet-tools now.  I have made some updates here which I haven't tested yet, awaiting fixes to chaosnet-bridge.  Now that fixes have appeared, I will resume testing rtape.

**Comment by larsbrinkhoff** [comment]
It is more agreeable to MacOS now?

**Comment by bictorv** [comment]
Compiling under macOS still gives the deprecation warning for daemon().

**Comment by larsbrinkhoff** [comment]
Updated to remove daemon call on \_\_APPLE\_\_.

**Comment by eswenson1** [comment]
> It is more agreeable to MacOS now?

Yes, I can now build master branch (with newly-merged rtape and install) on macOS without any errors.
