### ISSUE TITLE
Trying to use rtape on Ubuntu Linux bombs out

### ISSUE THREAD

**Issue by eswenson1** [Chaosnet/chaosnet-tools#4]
I can successfully start up rtape on Ubuntu linux.  However, once I attempt to connect to it with DUMP on ITS (EXA), I get this error:

```
../rtape -v
Peer : Unknown operation: 1891288768
$
```

I'm using the lars/rtape branch of the chaosnet-tools repo.  And I'm using the cleaning-windows branch of the chaosnet-bridge repo.

My ITS session looks like:

```
EXA>dump↑K!
DUMP  .448

_remote
TAPE SERVER HOST=5402
DRIVE=backup.tap
READ-ONLY? n
Remote mount failed: Cannot connect to remote tape server
_
```

I restarted rtape and tried again:

```
_remote
TAPE SERVER HOST=5402
DRIVE=backup.tape
READ-ONLY? n
.VAL 0; 4313>>PUSHJ 17,@77(3)   E.A. _ 0   ◊p
```

With the above error, I see in the rtape window this:
```
Open connection from 05464
Record stream version ok
Peer 05464: Connection closed
```

**Comment by larsbrinkhoff** [comment]
It no longer bombs out.
![Screenshot from 2023-11-02 08-19-18](https://github.com/Chaosnet/chaosnet-tools/assets/775050/3ad8e55a-48e0-4ac6-b87b-9a424d6f97bf)
